### ISSUE TITLE
minimum python version?

### ISSUE THREAD

**Issue by abubelinha** [bnm3k/polars-fuzzy-match#3]
I am trying to make fuzzy matches on Python 3.8 (Windows 7 64 bit), with polars 0.20.13 already installed

Any way of installing this package?  Looks like I need a higher Python version but that's the highest one I can use with this OS.
I wonder if there is any workaround 

Thanks
@abubelinha

**Comment by bnmoch3** [comment]
I don't think this package uses any feature that's specific to higher python version. Only work around off the top of my head is to lower the python version requirement. Let me attempt it and see if anything breaks

**Comment by bnmoch3** [comment]
Can you try out 0.1.3, I've lowered the python version requirement to 3.8, it should work. Update: I've just tested with python 3.8.13 albeit on Linux and it works: `pip install polars-fuzzy-match==0.1.3`

**Comment by abubelinha** [comment]
I still couldn't try it on Python 3.8 (Windows 7 64 bits).

But I can tell you `pip install polars-fuzzy-match` was also failing in another computer (Python 3.9, Windows 10) ... and now it just works:

- **yesterday:**
```
C:\python39\scripts\pip install polars-fuzzy-match
ERROR: Ignored the following versions that require a different python version: 0.1.2 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement polars-fuzzy-match (from versions: none)
ERROR: No matching distribution found for polars-fuzzy-match
```
- **today:**
```
C:\python39\scripts\pip install polars-fuzzy-match
Collecting polars-fuzzy-match
  Downloading polars_fuzzy_match-0.1.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Downloading polars_fuzzy_match-0.1.3-cp38-abi3-win_amd64.whl (2.8 MB)
   ---------------------------------------- 2.8/2.8 MB 4.2 MB/s eta 0:00:00
Installing collected packages: polars-fuzzy-match
Successfully installed polars-fuzzy-match-0.1.3
```
Thanks a lot!
I'll try this afternoon in the Python 3.8 machine and close the issue if it works (I suppose it should, looking to your last comment).

BTW I didn't specify 0.1.3 version but I guess it didn't matter.

**Comment by abubelinha** [comment]
Off-topic:  

In README you describe [Fzf-style search syntax](https://github.com/bnm3k/polars-fuzzy-match?tab=readme-ov-file#fzf-style-search-syntax) "_is taken almost verbatim from the Fzf README_".

Are you meaning this project? https://github.com/junegunn/fzf?#search-syntax

**Comment by abubelinha** [comment]
Hold on.  
Still on Python 3.9 machine, where I could successfully install but I couldn't run `usage.py` example. This line raises error:

`from polars_fuzzy_match import fuzzy_match_score
`
```Python
E:\Dropbox\python>c:\python39\python polarex.py
Traceback (most recent call last):
  File "E:\Dropbox\python\polarex.py", line 78, in <module>
    polarsfm_usage(); sys.exit()
  File "E:\Dropbox\python\polarex.py", line 11, in polarsfm_usage
    from polars_fuzzy_match import fuzzy_match_score
  File "c:\python39\lib\site-packages\polars_fuzzy_match\__init__.py", line 4, in <module>
    from polars.type_aliases import IntoExpr
ModuleNotFoundError: No module named 'polars.type_aliases'

```

The code:

```Python
def polarsfm_usage():
	""" Taken from https://github.com/bnm3k/polars-fuzzy-match/blob/master/examples/usage.py """
	import polars as pl
	from polars_fuzzy_match import fuzzy_match_score


	df = pl.DataFrame(
		{
			'strs': ['foo', 'foo quz BAR', 'baaarfoo', 'quz'],
		}
	)
	pattern = 'bar'
	out = (
		df.with_columns(
			score=fuzzy_match_score(
				pl.col('strs'),
				pattern,
			)
		)
		.filter(pl.col('score').is_not_null())
		.sort(by='score', descending=True)
	)
	print(out)

```

**Comment by abubelinha** [comment]
OK, I can confirm successful installation on Python 3.8 (Windows 7 64 bits).

Thanks a lot for your help
