### ISSUE TITLE
Update version via pip

### ISSUE THREAD

**Issue by jikac** [bnm3k/polars-fuzzy-match#7]
This is a great package and it's solved quite a few of my problems already. The most recent PR that updated functionality to polars 1.4.1 is what I needed to get it working.

Right now, when I install it via `pip install polars-fuzzy-match`, I'm getting the Mar 4, 2024 release. Could you push a new release to pypi? 🙏🏻

**Comment by bnmoch3** [comment]
I thought I had automated it via CI, let me do it manually asap

**Comment by bnmoch3** [comment]
@jikaczmarski can you retry right now with v0.1.5

**Comment by jikac** [comment]
> @jikaczmarski can you retry right now with v0.1.5

Works perfect! Thanks so much for your efforts.

**Comment by bnmoch3** [comment]
You're welcome
